name: Test
on: [push]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: npm install
      - name: Unit Tests
        run: npm test:unit
      - name: E2E Tests
        run: npm test:e2e --headless